-- La siguiente linea la debes agregar solo si tienes Oracle 18c
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- USER SQL
CREATE USER BuyBee IDENTIFIED BY buybee123
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER BuyBee QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO BuyBee ;
GRANT "CONNECT" TO BuyBee ;
ALTER USER BuyBee DEFAULT ROLE "RESOURCE","CONNECT";
