# Generated by Django 4.0.4 on 2022-06-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('cupon', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('foto', models.ImageField(null=True, upload_to='categorias')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEnvio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(max_length=128)),
                ('nombres', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.IntegerField(null=True)),
                ('foto_perfil', models.ImageField(null=True, upload_to='fotosPerfil')),
                ('suscrito', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.CharField(blank=True, max_length=1024)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('fecha_publicacion', models.DateField()),
                ('vistas', models.IntegerField()),
                ('compras', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyBeeApp.categoria')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyBeeApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='productosImagenes')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyBeeApp.productoventa')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BuyBeeApp.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyBeeApp.productoventa')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField(default=0)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyBeeApp.usuario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BuyBeeApp.estadopedido')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BuyBeeApp.usuario')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BuyBeeApp.estadoenvio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyBeeApp.pedido')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vendedor', to='BuyBeeApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BuyBeeApp.pedido')),
                ('producto', models.ManyToManyField(to='BuyBeeApp.productoventa')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='duenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyBeeApp.usuario'),
        ),
    ]
