# Generated by Django 4.0.4 on 2022-06-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuyBeeApp.detallepedido'),
        ),
    ]
