# Generated by Django 4.0.5 on 2022-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyBeeApp', '0002_categoria_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='suscrito',
            field=models.BooleanField(default=False),
        ),
    ]
